{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "minio.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 180m
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 230Mi
{{- end }}
