{{- if .Values.global.sfapm_celery.sftrace.clusterRoleBindingName }}
apiVersion: {{ include "autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sfapm.fullname" . }}-apm-celery-sftrace
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sfapm.fullname" . }}-apm-celery-sftrace
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        periodSeconds: {{ .Values.global.sfapm_celery.sftrace.autoscaling.scaleDownPeriod }}
        value: 1
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        periodSeconds: {{ .Values.global.sfapm_celery.sftrace.autoscaling.scaleUpPeriod }}
        value: 1
  minReplicas: {{ .Values.global.sfapm_celery.sftrace.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.sfapm_celery.sftrace.autoscaling.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: sftrace_queue_count
      target:
        type: AverageValue
        averageValue: {{ .Values.global.sfapm_celery.sftrace.autoscaling.averageValue }}
{{- end }}