{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cp-kafka-rest.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cp-kafka-rest.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metricName: kafka_rest_heap_utilization_pcnt
      targetAverageValue: 85
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: 450m
{{- end }}