{{- if .Values.autoscaling.enabled -}}
apiVersion: {{ include "autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sf-presto.fullname" . }}-worker
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: resource-manager
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sf-presto.fullname" . }}-worker
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleDownPeriod }}
        value: 1
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleUpPeriod }}
        value: 1
  minReplicas: {{ .Values.autoscaling.worker.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.worker.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: presto_queued_queries
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.worker.targetQueuedQueries }}
  - type: Pods
    pods:
      metric:
        name: presto_running_drivers
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.worker.targetRunningDrivers }}
{{- end }}

